### ISSUE TITLE
XP For the swords

### ISSUE THREAD

**Issue by noaskers** [nulli0n/SkillMeUp-spigot#1]
ENTITY_KILL 

With hostile mobs does not work
Right now people can just level up sword by spam clicking, I want to change it so they can only get xp for killing mobs instead of swining the sword

I tried this with the: ENTITY_KILL 

But it only works with PASSIVE mobs and it does not work with HOSTILE MOBS

**Comment by nulli0n** [comment]
You have to provide mob names when using ENTITY_KILL setting. Could you show your swords config?

**Comment by noaskers** [comment]
```yml
  kill_monsters:
    Name: Kill Monsters
    Description:
    - '#aefd5e✔#d4d9d8 Zombie'
    - '#aefd5e✔#d4d9d8 Creeper'
    - '#aefd5e✔#d4d9d8 Skeleton'
    - '#aefd5e✔#d4d9d8 Blaze'
    Icon:
      Material: IRON_SWORD
      Head_Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmVlODUxNDg5MmYzZDc4YTMyZTg0NTZmY2JiOGM2MDgxZTIxYjI0NmQ4MmYzOThiZDk2OWZlYzE5ZDNjMjdiMyJ9fX0=
    Type: ENTITY_KILL
    Values:
    - zombie
    - creeper
    - skeleton
    - blaze
    XP:
      Min: 3
      Max: 5
      Chance: 100.0
 ```
